# .github/workflows/ci.yml
name: Tests

on:
  push:
    branches: [ main, master, develop, test ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests with coverage
      run: npm run test:cov
      
    - name: Display coverage summary
      run: cat ./coverage/coverage-summary.json | jq '.total'